[package]
name = "Bevy-3D_Chess"
version = "0.2.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.1", features = ["jpeg"] }
bevy_picking = { version = "0.16.1" }
bevy_panorbit_camera = "0.28"
crossbeam-channel = "0.5"
futures-lite = "2.6"
#rand = "0.9"
num-traits = "0.2"
async-std = "1.13"

[profile.dev]
opt-level = 3

[features]
salewskiChessDebug = []
default_font = []
